apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
        - name: service-a
          image: your-docker-image-for-service-a
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_B_URL
              value: "http://service-b:8080" # Pointing to Service B
a
